### ISSUE TITLE
unsecure use of unitiated pointer

### ISSUE THREAD

**Issue by shemphys** [suspectedoceano/get_next_line#1]
in the files get_next_line.c and get_next_line_bonus.c > char *get_next_line(int fd) > in the read of the "if" statement you use &next_line before initating it. 
Isn't this a possible segfault?

Thank you for your work 😃

**Comment by suspectedoceano** [comment]
Hello friend! that line is just a gimmick to check file permissions, if you see i read 0 chars into the pointer address (which makes no sense 😁).
In all my tests this didn't seg fault, but indeed is no intellegibile now that i think about that 🧐
